# Generated by Django 5.0.6 on 2024-08-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_todoemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoemployee',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
