# Generated by Django 5.0.6 on 2024-08-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_todoemployee_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoemployee',
            name='by_ceo',
            field=models.BooleanField(default=False),
        ),
    ]
