# Generated by Django 5.0.6 on 2024-08-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_todoemployee_by_ceo'),
    ]

    operations = [
        migrations.CreateModel(
            name='reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
