# Generated by Django 5.0.6 on 2024-07-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceo_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoceo',
            name='date_Created',
            field=models.DateField(),
        ),
    ]
