# Generated by Django 5.0.6 on 2024-07-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceo_core', '0002_alter_todoceo_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoceo',
            name='date_Created',
            field=models.DateField(auto_now=True),
        ),
    ]
