# Generated by Django 5.0.6 on 2024-07-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceo_core', '0003_alter_todoceo_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoceo',
            name='task',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
