# Generated by Django 5.0.6 on 2024-07-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceo_core', '0004_alter_todoceo_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoceo',
            name='task',
            field=models.CharField(default='a', max_length=500),
            preserve_default=False,
        ),
    ]
